name: Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK (21)
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "temurin"
          architecture: x64

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          args: build
          gradle-version: 8.5
          build-root-directory: app

      - name: Start tests
        working-directory: ./app
        run: |
          chmod +x gradlew
          ./gradlew test

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: ./src/main/java
        with:
          coverageCommand: make report
          coverageLocations: ./jacocoReports/jacocoTestReport.xml:jacoco